# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaPuppy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('image_src', models.CharField(blank=True, max_length=1000, null=True)),
                ('breed', models.CharField(blank=True, max_length=250, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('tricks', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
