# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaPuppy', '0003_auto_20170219_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
