# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentaPuppy', '0004_dogs_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='dog_pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=500)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='dogs',
            name='image_src',
        ),
        migrations.AddField(
            model_name='dog_pictures',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentaPuppy.dogs'),
        ),
    ]
