# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaPuppy', '0006_auto_20170219_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog_pictures',
            name='image',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
