# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaPuppy', '0007_dog_pictures_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog_pictures',
            name='image',
            field=models.ImageField(upload_to=b'static/img'),
        ),
    ]
