# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-22 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plr_app', '0003_live_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live_document',
            name='category',
        ),
    ]
