# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clothing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_id', models.CharField(blank=True, max_length=100, null=True)),
                ('small_url', models.CharField(blank=True, max_length=300, null=True)),
                ('large_url', models.CharField(blank=True, max_length=300, null=True)),
                ('gender', models.BooleanField(default=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='outfit_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transform_matrix', models.CharField(blank=True, max_length=300, null=True)),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareWear.clothing')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareWear.outfit')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='outfit',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareWear.profile'),
        ),
    ]
