# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='cloth_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
