# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0002_clothing_cloth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='aff_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clothing',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clothing',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
