# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0006_auto_20170326_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
