# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0007_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
