# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0008_outfit_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='canvas_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='canvas_width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
