# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 04:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0014_auto_20170409_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 10, 4, 14, 44, 15000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
