# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0022_auto_20170429_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='colors',
        ),
    ]
