# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0023_delete_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default=b'../static/img/anonymous-user.png', max_length=200),
        ),
    ]
