# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0024_auto_20170508_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('cart_items', models.ManyToManyField(to='shareWear.cartItems')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shareWear.profile')),
            ],
        ),
    ]
