# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0025_cart_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='cloth_sub_type',
            field=models.CharField(default=b'all', max_length=100),
        ),
    ]
