# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-16 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0027_profile_favorite_clothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_recruited',
            field=models.ManyToManyField(related_name='recruitedProfiles', to='shareWear.profile'),
        ),
    ]
