# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-28 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0029_blog_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='content',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='body',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_post',
            name='slug',
            field=models.SlugField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
