# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-28 05:25
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shareWear', '0030_auto_20170527_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='body',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='body_content',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
    ]
